### ISSUE TITLE
Support on Pytorch 0.4.0

### ISSUE THREAD

**Issue by habenben** [mkmenta/ColorMNIST#1]
I tried to produce 'both' mode of the ColorMNIST with Pytorch 0.4.0, but it only colorized background. Is there any way to resolve such issue?

**Comment by mkmenta** [comment]
Hi, it works for me. Here you have a way to get a sample to test it:
```
if __name__ == "__main__":
    d = ColorMNIST(color='both', split='train', path='path_to_mnist')
    im, _ = d[2]
    pilim = transforms.ToPILImage()(im)
    pilim.save('sample.png')
```
and I got
![sample](https://user-images.githubusercontent.com/18461246/61955263-e1e26800-afba-11e9-88cf-7e09956c366f.png)

Also, PyTorch version shouldn't affect, the coloring is done with a numpy array.

**Comment by habenben** [comment]
Hi, thank you for your reference. I found that the issue I was troubling with was raised from my code, and now resolved it. Thank you!
